# Generated by Django 4.1.7 on 2023-05-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
