# Generated by Django 4.1.7 on 2023-05-18 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='category',
            new_name='Matiere',
        ),
    ]
