# Generated by Django 4.1.7 on 2023-05-18 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_rename_category_cours_matiere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='enseigant',
            new_name='author',
        ),
    ]
