# Generated by Django 4.1.7 on 2023-05-18 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_rename_enseigant_cours_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='Matiere',
        ),
        migrations.DeleteModel(
            name='matiere',
        ),
    ]
